### ISSUE TITLE
Broken since Ember 5 (TypeError: (intermediate value).property is not a function)

### ISSUE THREAD

**Issue by msebald** [Canapin/Discourse-donation-icon-toggle#2]
Since the Discourse upgrade to Ember 5 I got a red error/warning message about the donation-icon-toggle. And in development console I see the following:

```
[THEME 52 'donation icon toggle'] TypeError: (intermediate value).property is not a function
    at theme-field-380-common-html-script-1.js:61:13
    at Ne (plugin-api.js:2760:12)
    at Object.initialize (theme-field-380-common-html-script-1.js:15:22)
    at n.initialize (app.js:208:28)
    at index.js:145:1
    at e.each (dag-map.js:191:1)
    at e.walk (dag-map.js:120:1)
    at e.each (dag-map.js:66:1)
    at e.topsort (dag-map.js:72:1)
    at e._runInitializer (index.js:158:1)
    at e.runInstanceInitializers (index.js:143:1)
    at u._bootSync (instance.js:86:1)
    at e.didBecomeReady (index.js:602:1)
    at invoke (backburner.js.js:280:1)
    at h.flush (backburner.js.js:197:1)
    at p.flush (backburner.js.js:358:1)
    at B._end (backburner.js.js:798:1)
    at B._boundAutorunEnd (backburner.js.js:523:1)
k @ client-error-handler.js:125
```

As I am completely lost in this programming language I need to open up a issue here. My hope is that you need it for your own forums as well. ;-)

If any more information is needed, I am happy to provide it.

**Comment by Canapin** [comment]
I'm not maintaining this component, I don't need the component anymore, it was only useful to allow users to disable the icon in their preference. Now I only use https://meta.discourse.org/t/custom-header-links-icons/86307 for my needs. I'll archive this repo.
